require "plugins.theme"
require "plugins.lualine"
require "plugins.gitsigns"
require "plugins.oil"
require "plugins.conform"
require "plugins.treesitter"
require "plugins.telescope"

require "plugins.completion"
require "plugins.lsp"
